### ISSUE TITLE
repo dead?

### ISSUE THREAD

**Issue by Lisendra** [andriichuk/laravel-vue-js-starter-kit#7]
Hi,
this repo seem actually very nice, i'm been looking on the net for a quality laravel/vue.js starter kit, mostly you will find tutorials, or blogs post, some goes in the right direction, some are full of non sense (seem to be copy/past of someone else work but not adapted), but none provide a base for docker to be able to mold to other projects.

This repo seem to be a very nice start, could we expect updates, maybe a Readme, i would also gladly contribute if you open for cooperation,

Best regards.

**Comment by andriichuk** [comment]
@Lisendra Hi! Thanks for your interest in the repository. Yes I am planning resolve security issues, upgrade dependencies and maybe switch to Laravel Sail docker version.

**Comment by andriichuk** [comment]
Hi @Lisendra! Check new [readme](https://github.com/andriichuk/laravel-vue-js-starter-kit/blob/master/README.md)
